app/models.py
from datetime import datetime

from app import db


class Entries(db.Model):
    __tablename__ = "entries"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    comment = db.Column(db.Text(), nullable=False)
    created = db.Column(db.DateTime(), nullable=False)

    def __init__(self, name, comment):
        self.name = name
        self.comment = comment
        self.created = datetime.utcnow()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from settings import config_dict

db = SQLAlchemy()


def create_app(config=config_dict["dev"]):
    app = Flask(__name__)
    app.config.from_object(config)

    db.init_app(app)

    if app.config.get("PROMETHEUS_METRICS") == "enable":
        from prometheus_flask_exporter import PrometheusMetrics

        PrometheusMetrics(app)

    from app.main.views import blueprint as main
    from app.api import blueprint as api
    from app.entries.views import blueprint as entries
    from app.health.views import blueprint as health

    app.register_blueprint(main)
    app.register_blueprint(api, url_prefix="/api/v1")
    app.register_blueprint(entries, url_prefix="/entries")
    app.register_blueprint(health, url_prefix="/health")

    from app.main.errors import page_not_found

    app.register_error_handler(404, page_not_found)

    return app

app/api/__init__.py
from flask import Blueprint
from flask_restx import Api

from app.api.entries import api as entries

blueprint = Blueprint("api", __name__)

api = Api(
    blueprint, title="Guestbook", version="1.0", description="Guestbook simple API"
)

api.add_namespace(entries)

app/entries/views.py
from dateutil import parser
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from app.api.entries import EntryList


blueprint = Blueprint("entries", __name__, template_folder="templates")


@blueprint.route("/")
def show_entries():
    """
    List of entries.
    """
    return render_template("show_entries.html", entries=EntryList().get())


@blueprint.route("/new", methods=["GET", "POST"])
def new_entry():
    """
    Form for new entry.
    """
    if request.method == "POST":
        data = {
            "name": request.form.get("name", "Anonymous"),
            "comment": request.form["comment"],
        }
        EntryList().post(data)
        return redirect(url_for("entries.show_entries"))
    return render_template("new.html")


@blueprint.app_template_filter("strftime")
def _jinja2_filter_datetime(date, fmt=None):
    date = parser.parse(date)
    native = date.replace(tzinfo=None)
    format = "%b %d, %Y"
    return native.strftime(format)

app/health/views.py
from flask import Blueprint
from healthcheck import HealthCheck

from app import db


blueprint = Blueprint("health", __name__, template_folder="templates")
health = HealthCheck()


def postgres_available():
    """
    Return True and "postgres ok" if connection to postgres is successfull
    """
    is_db_ok = True
    output = "postgres ok"

    try:
        db.session.execute("SELECT 1")
    except Exception as e:
        output = str(e)
        is_db_ok = False

    return is_db_ok, output


health.add_check(postgres_available)
blueprint.add_url_rule("/", "health", view_func=health.run)

app/main/views.py
from flask import Blueprint
from flask import render_template

blueprint = Blueprint("main", __name__, template_folder="templates")


@blueprint.route("/")
def home():
    return render_template("index.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A Python Flask web application that allows visitors to leave a public comment without creating a user account." />
    <title>{% block title %}{% endblock %}The Final project .. Guestbook</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/toggle-bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/toggle-bootstrap-dark.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/toggle-bootstrap-print.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
</head>

<body class="bootstrap">
    <header class="sticky-top">
        <nav class="navbar navbar-expand-lg border-bottom shadow-sm mb-4 bg-light">

            <a class="navbar-brand h1" href="/">
                <i class="fas fa-book"></i> Guestbook
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="mr-auto"></div>
                <div class="navbar-nav">
                    <a href="{{ url_for('main.home') }}" class="nav-item nav-link">Home</a>
                    <a href="{{ url_for('entries.show_entries') }}" class="nav-item nav-link">Entries</a>
                    <a href="https://github.com/ahmed-ahmedd/final-guestbook.git" class="nav-item nav-link mr-3">GitHub</a>
                    <a href="{{ url_for('entries.new_entry') }}" class="btn btn-outline-primary mr-3" role="button">Write in the Guestbook</a>
                    <div class="dark-mode pt-1">
                        <span class="icon-sun"></span>
                        <label class="switch">
                            <input type="checkbox" onclick="SwapThemes();" id="toggle-dark-mode">
                            <span class="slider round"></span>
                        </label>
                        <span class="icon-moon-o"></span>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer class="fixed-bottom">
        <nav class="navbar justify-content-center border-top mt-4 bg-light">
            <a href="/api/v1" class="nav-item nav-link">API</a>
            <a href="/metrics" class="nav-item nav-link">Metrics</a>
            <a href="/health" class="nav-item nav-link">Health</a>
        </nav>
        <div class="footer-copyright text-center py-3 bg-light">
            Made For <span style="color:#ec3935;">&#9829;</span> by
            <a href="https://github.com/ahmed-ahmedd/final-guestbook.git" target="_blank" rel="noopener noreferrer">Depi, The Final Project</a>
        </div>
    </footer>
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/fgEmojiPicker.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>